// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmIwrMyRkzUfTBK2j__mloCRCW0KYuQhI',
    appId: '1:345468939113:web:4cf68ac21daf7974a1ebf8',
    messagingSenderId: '345468939113',
    projectId: 'daily-journal-app-40530',
    authDomain: 'daily-journal-app-40530.firebaseapp.com',
    storageBucket: 'daily-journal-app-40530.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALVxdkkqF8I0uRKZwa9EnTdItbMFCWPaE',
    appId: '1:345468939113:android:6a7bf52d97373d62a1ebf8',
    messagingSenderId: '345468939113',
    projectId: 'daily-journal-app-40530',
    storageBucket: 'daily-journal-app-40530.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjKptrJOnxDuKayY5kL-6smylcAMAujcI',
    appId: '1:345468939113:ios:3a2366621dcf93b4a1ebf8',
    messagingSenderId: '345468939113',
    projectId: 'daily-journal-app-40530',
    storageBucket: 'daily-journal-app-40530.firebasestorage.app',
    iosBundleId: 'com.example.dailyJournalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjKptrJOnxDuKayY5kL-6smylcAMAujcI',
    appId: '1:345468939113:ios:3a2366621dcf93b4a1ebf8',
    messagingSenderId: '345468939113',
    projectId: 'daily-journal-app-40530',
    storageBucket: 'daily-journal-app-40530.firebasestorage.app',
    iosBundleId: 'com.example.dailyJournalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmIwrMyRkzUfTBK2j__mloCRCW0KYuQhI',
    appId: '1:345468939113:web:72501c32a6713deba1ebf8',
    messagingSenderId: '345468939113',
    projectId: 'daily-journal-app-40530',
    authDomain: 'daily-journal-app-40530.firebaseapp.com',
    storageBucket: 'daily-journal-app-40530.firebasestorage.app',
  );
}
